name: Builds

on:
  workflow_dispatch:

jobs:
  builds-android:
    name: Build android-aarch64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Build android-aarch64
        run: |
          chmod +x scripts/build-android-arm64.sh
          scripts/build-android-arm64.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csso-android-aarch64
          path: ./output/*
